---
title: "DataWrangling"
output: html_document
---

```{r}
install.packages("tidyverse") #install.packages("tidyverse") couldn't install bc of lubridate
library(dplyr)
library(tidyr)
## read gapminder csv. Note the readr:: prefix identifies which package it's in
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

#inspect the data
#look at data
gapminder
head(gapminder) #gives first 6 by default
tail(gapminder)
str(gapminder) #type of data
summary(gapminder) #min max and mean by column
install.packages("skimr")
library(skimr)
skimr::skim(gapminder)
names(gapminder)
dim(gapminder) #dimensions (rows, columns)
ncol(gapminder)
c(nrow(gapminder),ncol(gapminder))

##dplyr
#filter by rows
filter(gapminder, lifeExp<29)
filter(gapminder, country =="Mexico")
filter(gapminder, country %in% c("Mexico","Peru"))
filter(gapminder, country=="Mexico", year==2002)
Sweden <- filter(gapminder, country=="Sweden")
mean(Sweden$lifeExp)

#select by columns
select(gapminder, year, lifeExp)
select(gapminder, -continent, -lifeExp) #select columns, excluding continent and lifExp
#use select and filter together
gap_cambodia <- filter(gapminder, country=="Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, lifeExp)
```

The pipe operator
```{r}
gapminder %>% head()
#this is equivalent to head(gapminder)
gapminder %>% head(3)
#is equivalent to head(gapminder,3)

#instead of using this:
gap_cambodia <- filter(gapminder, country=="Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, lifeExp)

#use this:
gap_cambodia <- gapminder %>% 
  filter(country=="Cambodia") %>% 
  select(-continent, -lifeExp)
#read the pipe %>% as "and then"

#mutate adds new variables
gapminder %>% 
  mutate(index = 1:nrow(gapminder)) #index is a new variable (colum) we are creating. =1:nrow is what goes in the variable. It is an index for observation 1,2,3...n

gapminder %>% 
  mutate(gdp= pop*gdpPercap)

#Find the maximum gdpPerCap of Egypt and Vietnam (one max for both) and create a new column
gapVE <- gapminder %>% 
  filter(country =="Vietnam" | country=="Egypt") %>%
  mutate(maxGDPpercap=max(gdpPercap))
#or
gapminder %>% 
  filter(country %in% c("Egypt","Vietnam")) %>% 
  mutate (gdp = pop*gdpPercap, #use a comma in a mutate function to have it complete 2 functions
          max_gdp = max(gdp))

gap_summarize <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp=pop*gdpPercap) %>% 
  summarize(max_gdp=max(gdp)) %>% 
  ungroup() %>% 
  arrange(desc(max_gdp))

## read in the data. (same URL as yesterday, with co2.csv instead of gapminder.csv)
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")

co2 %>% head()
co2 %>% dim() #12 observations

##create a new gapminder variable with only 2007 data
gap__2007 <- gapminder %>% 
  filter(year==2007)
gap_2007 %>% dim() #142 obersvations

#left join gap_2007 to co2
lj <- left_join(gap__2007, co2, by= "country")
#another way using the %>% 
lf<-gap__2007 %>% 
  left_join(co2, by="country")

##right_join gap__2007 to co2
rj <- right_join(gap__2007, co2)


  ```